export const COUNTRIES = [
  { code: "AT", name: "אוסטריה" },
  { code: "AU", name: "אוסטרליה" },
  { code: "UA", name: "אוקראינה" },
  { code: "AE", name: "איחוד האמירויות הערביות" },
  { code: "IT", name: "איטליה" },
  { code: "IE", name: "אירלנד" },
  { code: "EE", name: "אסטוניה" },
  { code: "AR", name: "ארגנטינה" },
  { code: "US", name: "ארצות הברית" },
  { code: "BG", name: "בולגריה" },
  { code: "BE", name: "בלגיה" },
  { code: "BR", name: "ברזיל" },
  { code: "GB", name: "בריטניה" },
  { code: "DE", name: "גרמניה" },
  { code: "DK", name: "דנמרק" },
  { code: "NL", name: "הולנד" },
  { code: "HU", name: "הונגריה" },
  { code: "MK", name: "הרפובליקה המקדונית של צפון מקדוניה" },
  { code: "TR", name: "טורקיה" },
  { code: "TW", name: "טייוואן" },
  { code: "GR", name: "יוון" },
  { code: "JP", name: "יפן" },
  { code: "IL", name: "ישראל" },
  { code: "LU", name: "לוקסמבורג" },
  { code: "LV", name: "לטביה" },
  { code: "LI", name: "ליכטנשטיין" },
  { code: "MY", name: "מלזיה" },
  { code: "MT", name: "מלטה" },
  { code: "MX", name: "מקסיקו" },
  { code: "NO", name: "נורבגיה" },
  { code: "NZ", name: "ניו-זילנד" },
  { code: "CN", name: "סין" },
  { code: "SI", name: "סלובניה" },
  { code: "SK", name: "סלובקיה" },
  { code: "ES", name: "ספרד" },
  { code: "RS", name: "סרביה" },
  { code: "PL", name: "פולין" },
  { code: "PT", name: "פורטוגל" },
  { code: "FI", name: "פינלנד" },
  { code: "CZ", name: "צ'כיה" },
  { code: "FR", name: "צרפת" },
  { code: "CO", name: "קולומביה" },
  { code: "KR", name: "קוריאה" },
  { code: "CA", name: "קנדה" },
  { code: "CY", name: "קפריסין" },
  { code: "HR", name: "קרואטיה" },
  { code: "RO", name: "רומניה" },
  { code: "SE", name: "שוודיה" },
  { code: "CH", name: "שוויץ" },
  { code: "TH", name: "תאילנד" },
];

export const GTM_ID = "GTM-KMZ4JRVD";

export const WEBHOOK_URL =
  "https://hooks.zapier.com/hooks/catch/12961765/uxt7tm2/";
